FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY requirements.txt .

RUN uv pip install --system --no-cache -r requirements.txt

COPY . .

EXPOSE 8001
CMD ["uvicorn", "apps.patient_api.main:app", "--host", "0.0.0.0", "--port", "8001"]
